SYMBOL        = "BTCUSDT"
LOT_SIZE      = 0.001        # BTC per order (Binance testnet min)
QUOTE_INTERVAL = 5           # seconds between requotes
DELTA         = 15.0         # half-spread in USD (tight for testnet liquidity)
GAMMA         = 50.0         # AS inventory skew sensitivity ($/BTC)
DELTA_0       = 10.0         # AS max additional half-spread at session start
DELTA_MIN     = 3.0          # AS minimum half-spread
SESSION_STEPS = 1440         # steps per session (reset inventory urgency)
MAX_INVENTORY = 0.05         # hard inventory cap in BTC (relative to starting position)
LOG_INTERVAL  = 30           # seconds between P&L log lines
